### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by iambenmitchell** [arturgrigor/IPAPI#1]
Hi, the site does not have HTTPS. Transport security will block it. In ios12 you cannot disable Transport security.

**Comment by syedrazackimran** [comment]
@MrBenFTW 
I am also facing the same problem I added a line of 

```
<key>NSAppTransportSecurity</key>
<dict>
  <!--Include to allow all connections (DANGER)-->
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>

```
in PLIST. still, I am facing an error. kindly do needfully

**Comment by arturgrigor** [comment]
HTTPS is now supported by this library but you need to register for the ["Pro" plan](https://members.ip-api.com) on the IP-API.com website to get an API key for that.
