### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by VamsiKrishna1805** [arturgrigor/IPAPI#3]
CocoaPods could not find compatible versions for pod "IPAPI":
  In Podfile:
    IPAPI (~> 2.1)

None of your spec sources contain a spec satisfying the dependency: `IPAPI (~> 2.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by arturgrigor** [comment]
You can install version 3.0.0 which is now available using CocoaPods.
